### ISSUE TITLE
clair restarts repeatedly when fetching vulnerabilty updates

### ISSUE THREAD

**Issue by ahlae** [bitnami/bitnami-docker-harbor-clair#2]
**Description**

When deploying helm chart harbor-10.2.2 with the clair vulnerability scanner enabled the clair pod panics and keeps restarting when trying to fetch updates.

**Steps to reproduce the issue:**

1. Install harbor helm chart 10.2.2 with clair.enabled=true
2. Watch clair pod logs and wait for fetching updates

```
 10:13:44.42 
 10:13:44.42 Welcome to the Bitnami harbor-clair container
 10:13:44.43 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-harbor-clair
 10:13:44.43 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-harbor-clair/issues
 10:13:44.44 
 10:13:44.44 INFO  ==> ** Starting Harbor Clair setup **
 10:13:44.46 INFO  ==> Validating Harbor Clair settings...
 10:13:44.47 INFO  ==> No custom certificates were installed in the system
 10:13:44.47 INFO  ==> Waiting for PostgreSQL to be available at harbor-postgresql:5432...
 10:13:44.51 INFO  ==> ** Harbor Clair setup finished! **

 10:13:44.52 INFO  ==> ** Starting Harbor Clair **
{"Event":"running database migrations","Level":"info","Location":"pgsql.go:216","Time":"2021-07-22 10:13:44.570604"}
{"Event":"database migration ran successfully","Level":"info","Location":"pgsql.go:223","Time":"2021-07-22 10:13:44.595892"}
{"Event":"starting health API","Level":"info","Location":"api.go:85","Time":"2021-07-22 10:13:44.596371","port":6061}
{"Event":"updater service started","Level":"info","Location":"updater.go:83","Time":"2021-07-22 10:13:44.596450","lock identifier":"e39c0a32-0e60-45a6-97e2-ef3a4d51eabe"}
{"Event":"notifier service is disabled","Level":"info","Location":"notifier.go:77","Time":"2021-07-22 10:13:44.597098"}
{"Event":"starting main API","Level":"info","Location":"api.go:52","Time":"2021-07-22 10:13:44.597210","port":6060}
{"Event":"updating vulnerabilities","Level":"info","Location":"updater.go:192","Time":"2021-07-22 10:20:51.730505"}
{"Event":"fetching vulnerability updates","Level":"info","Location":"updater.go:239","Time":"2021-07-22 10:20:51.730667"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"ubuntu.go:85","Time":"2021-07-22 10:20:51.730995","package":"Ubuntu"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"debian.go:63","Time":"2021-07-22 10:20:51.731735","package":"Debian"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"oracle.go:119","Time":"2021-07-22 10:20:51.754804","package":"Oracle Linux"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"rhel.go:92","Time":"2021-07-22 10:20:51.755118","package":"RHEL"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"alpine.go:52","Time":"2021-07-22 10:20:51.755592","package":"Alpine"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"amzn.go:84","Time":"2021-07-22 10:20:51.756039","package":"Amazon Linux 2"}
{"Event":"Start fetching vulnerabilities","Level":"info","Location":"amzn.go:84","Time":"2021-07-22 10:20:51.801207","package":"Amazon Linux 2018.03"}
panic: runtime error: slice bounds out of range [25:24]

goroutine 315 [running]:
github.com/coreos/clair/ext/vulnsrc/rhel.toFeatureVersions(0xc00009a590, 0x2, 0xc000130078, 0x1, 0x1, 0xc0002820d0, 0x1, 0x1, 0x203000, 0x203000, ...)
	/bitnami/blacksmith-sandox/clair-2.1.6/pkg/mod/github.com/coreos/clair@v2.1.0+incompatible/ext/vulnsrc/rhel/rhel.go:292 +0xc46
github.com/coreos/clair/ext/vulnsrc/rhel.parseRHSA(0x7f6418078ac0, 0xc0001f21e0, 0xc0001f21e0, 0x7f6418078ac0, 0xc0001f21e0, 0x8ea73a, 0x4)
	/bitnami/blacksmith-sandox/clair-2.1.6/pkg/mod/github.com/coreos/clair@v2.1.0+incompatible/ext/vulnsrc/rhel/rhel.go:182 +0x1eb
github.com/coreos/clair/ext/vulnsrc/rhel.(*updater).Update(0xc099c8, 0x98e6a0, 0xc000070c40, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/bitnami/blacksmith-sandox/clair-2.1.6/pkg/mod/github.com/coreos/clair@v2.1.0+incompatible/ext/vulnsrc/rhel/rhel.go:145 +0x6c5
github.com/coreos/clair.fetch.func1(0x98e6a0, 0xc000070c40, 0xc00012eb88, 0xc000101080, 0x8ea9ee, 0x4, 0x982760, 0xc099c8)
	/bitnami/blacksmith-sandox/clair-2.1.6/pkg/mod/github.com/coreos/clair@v2.1.0+incompatible/updater.go:243 +0xa8
created by github.com/coreos/clair.fetch
	/bitnami/blacksmith-sandox/clair-2.1.6/pkg/mod/github.com/coreos/clair@v2.1.0+incompatible/updater.go:242 +0x1b0
```

**Describe the results you received:**

Unusable clair security scanner in harbor since it constantly restarts.

**Describe the results you expected:**

Clair scanning images in the harbor image repo.

**Version**

- Output of `docker version`:

```
Client:
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.13.8
 Git commit:        afacb8b7f0
 Built:             Fri Dec 18 12:15:19 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.8
  Git commit:       afacb8b7f0
  Built:            Fri Dec  4 23:02:49 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.5.2-0ubuntu1~20.04.2
  GitCommit:        
 runc:
  Version:          spec: 1.0.2-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        
```

- Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 114
  Running: 80
  Paused: 0
  Stopped: 34
 Images: 78
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: systemd
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 
 runc version: 
 init version: 
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-64-generic
 Operating System: Ubuntu 20.04.1 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 23.78GiB
 Name: kube04
 ID: T44S:KH3Z:5HNE:O7J6:KIAQ:DTDU:Q32C:M6UP:TBNA:YARE:52A4:SB4Z
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

This is a deployment running onprem on a 3 node kubernetes cluster.

**Comment by migruiz4** [comment]
Hi @ahlae,

Thank you for reporting this issue.

I was able to reproduce this issue using the latest version of the Helm chart 10.2.3 and the latest version of the `bitnami/harbor-clair` image.

I think this is directly related to this issue https://github.com/quay/clair/issues/1249, which is apparently fixed in Clair `2.1.7`.

The following logs make me think that due to an internal issue, the Clair image is using Clair 2.1.6 when it should be using the latest version of Clair.

```

panic: runtime error: slice bounds out of range [25:24]

goroutine 70 [running]:
github.com/coreos/clair/ext/vulnsrc/rhel.toFeatureVersions(0xc01dd98000, 0x2, 0xc01d7d06b8, 0x1, 0x1, 0xc01dd34b60, 0x1, 0x1, 0x203007, 0x203007, ...)
        /bitnami/blacksmith-sandox/clair-2.1.6/pkg/mod/github.com/coreos/clair@v2.1.0+incompatible/ext/vulnsrc/rhel/rhel.go:292 +0xc46
github.com/coreos/clair/ext/vulnsrc/rhel.parseRHSA(0x7f3c5c4f9700, 0xc01dd7e600, 0xc01dd7e600, 0x7f3c5c4f9700, 0xc01dd7e600, 0x8ea73a, 0x4)
        /bitnami/blacksmith-sandox/clair-2.1.6/pkg/mod/github.com/coreos/clair@v2.1.0+incompatible/ext/vulnsrc/rhel/rhel.go:182 +0x1eb
github.com/coreos/clair/ext/vulnsrc/rhel.(*updater).Update(0xc099c8, 0x98e6a0, 0xc00009c840, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /bitnami/blacksmith-sandox/clair-2.1.6/pkg/mod/github.com/coreos/clair@v2.1.0+incompatible/ext/vulnsrc/rhel/rhel.go:145 +0x6c5
github.com/coreos/clair.fetch.func1(0x98e6a0, 0xc00009c840, 0xc0001a64b0, 0xc0001be900, 0x8ea9ee, 0x4, 0x982760, 0xc099c8)
        /bitnami/blacksmith-sandox/clair-2.1.6/pkg/mod/github.com/coreos/clair@v2.1.0+incompatible/updater.go:243 +0xa8
created by github.com/coreos/clair.fetch
        /bitnami/blacksmith-sandox/clair-2.1.6/pkg/mod/github.com/coreos/clair@v2.1.0+incompatible/updater.go:242 +0x1b0
```

For reference, these logs were generated using `bitnami/harbor-clair:2.3.1-debian-10-r1`

I have created an internal task to investigate this issue and we will get back to you as soon as possible.

**Comment by MatthiasHertel** [comment]
@migruiz4 

any news here ?

**Comment by migruiz4** [comment]
Hi @MatthiasHertel,

I'm sorry but we couldn't address this issue yet. We will let you know as soon as the issue is fixed. 

Sorry for the inconvenience.

**Comment by MatthiasHertel** [comment]
Hi @migruiz4 

thx for your  "stay-tuned" here - no prob - i just want to let u know - the issue is still present 

i guess u let me know if the issue is solved ...

my current rollout release (i will upgrade to 11.0.3 today):

```
 λ helm ls -A | grep harbor
lb-01-harbor-01 lb-01           22              2021-09-08 08:03:34.337060893 +0200 CEST        deployed        harbor-10.2.11                  2.3.2      
```

and the clair container still dies - at moment i use trivy:
![image](https://user-images.githubusercontent.com/8426566/135803239-ac8e66a8-7ea8-4807-b328-380deb3aefc6.png)

**Comment by Mauraza** [comment]
Hi @MatthiasHertel,

Thanks for reporting. We will continue investigating.

**Comment by goriparthivamsi** [comment]
Any update on this?

**Comment by migruiz4** [comment]
Hi @goriparthivamsi,

I'm sorry for the late response. Because Harbor Clair was deprecated in version 2.2 this got lower priority compared to other tasks.

Although, we haven't abandoned this and will let you know about any updates.

**Comment by DooDleWilk** [comment]
If I understand it right, Clair will do a git clone operation against the CVE repo, as follow :
`git clone https://git.launchpad.net/ubuntu-cve-tracker/`
Just launch ANY container, and type the same command and you'll receive:
`
docker run -it ubuntu /bin/bash
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
08c01a0ec47e: Pull complete 
Digest: sha256:669e010b58baf5beb2836b253c1fd5768333f0d1dbcb834f7c07a4dc93f474be
Status: Downloaded newer image for ubuntu:latest
root@1ae23258d295:/# apt update
Get:1 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
[...]      
Reading state information... Done
9 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@1ae23258d295:/# apt install git
Reading package lists... Done
[...]
done.
root@1ae23258d295:/# git clone https://git.launchpad.net/ubuntu-cve-tracker/
Cloning into 'ubuntu-cve-tracker'...
error: RPC failed; HTTP 503 curl 22 The requested URL returned error: 503
fatal: the remote end hung up unexpectedly
`

I don't think this is a Clair issue...

**Comment by migruiz4** [comment]
Hi!

A new version of the `bitnami/harbor-clair` image has been released fixing this issue.

Please give the image `bitnami/harbor-clair:2.4.1-debian-10-r69` a try and let me know if the issue is solved.

**Comment by MatthiasHertel** [comment]
@migruiz4 

thx i give the new image a shot and let u know if the issue here is solved

**Comment by rafariossaa** [comment]
Thanks @MatthiasHertel, don't hesitate to comeback and share your findings.
